name: "[5.10] ACE2/ACEPRO Build"

on:
  workflow_dispatch:
    inputs:
      ace2:
        description: "构建 ace2"
        type: boolean
        default: false
      acepro:
        description: "构建 acepro"
        type: boolean
        default: false

jobs:
  ace2-build:
    if: ${{ github.event.inputs.ace2 == 'true' }}
    uses: ./.github/workflows/ace2.yml
    secrets: inherit

  acepro-build:
    if: ${{ github.event.inputs.acepro == 'true' }}
    uses: ./.github/workflows/acepro.yml
    secrets: inherit
