name: OnePlus_ace2
on:
  workflow_call:
    inputs:
      CPU:
        type: string
        required: false
        default: 'sm8475'
      FEIL:
        type: string
        required: false
        default: 'oneplus_ace2_v'
      CPUD:
        type: string
        required: false
        default: 'taro'
      ANDROID_VERSION:
        type: string
        required: false
        default: 'android12'
      KERNEL_VERSION:
        type: string
        required: false
        default: '5.10'
      KERNEL_NAME:
        type: string
        required: false
        default: '-android12-9-0-g0a04ff961c85'
      kernelsu_variant:
        type: string
        required: false
        default: 'SukiSU-Ultra'
      kernelsu_version:
        type: string
        required: false
        default: 'main'
      SUSFS_ENABLED:
        type: string
        required: false
        default: 'true'
      VFS_patch_ENABLED:
        type: string
        required: false
        default: 'enable'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Configure Git
        run: |
         git config --global user.name "ychenxuan"
         git config --global user.email "3494167979@qq.com"

      - name: Install dependencies
        run: |
         sudo apt update && sudo apt upgrade -y
         sudo apt install -y python3 git curl

      - name: Install repo tool
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
         mkdir kernel_workspace && cd kernel_workspace
         repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ inputs.CPU }} -m ${{ inputs.FEIL }}.xml --depth=1
         repo --trace sync -c -j$(nproc --all) --no-tags
         rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
         rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
         sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion || true
         sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion || true
      
      - name: SukiSU-Ultra & SukiSU version
        if: ${{ inputs.kernelsu_variant == 'SukiSU-Ultra' || inputs.kernelsu_variant == 'SukiSU' }}
        run: |
          if [[ "${{ inputs.kernelsu_version }}" == "tag" ]]; then
            echo "BRANCH=-" >> $GITHUB_ENV
          elif [[ "${{ inputs.kernelsu_version }}" == "main" ]]; then
            echo "BRANCH=-s susfs-dev" >> $GITHUB_ENV
          fi

      - name: Add SukiSU-Ultra
        if: ${{ inputs.kernelsu_variant == 'SukiSU-Ultra' }}
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash ${{ env.BRANCH }}
          cd ./KernelSU
          KSU_VERSION=$(expr $(git rev-list --count main) + 10606)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: Add SukiSU
        if: ${{ inputs.kernelsu_variant == 'SukiSU' }}
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/KernelSU/main/kernel/setup.sh" | bash ${{ env.BRANCH }}
          cd ./KernelSU
          KSU_VERSION=$(expr $(git rev-list --count main) + 10606)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
          
      - name: Set up SUSFS & apply patches
        run: |
         set -e

         cd kernel_workspace
         git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}
         git clone --depth=1 https://github.com/ExmikoN/SukiSU_patch.git
         cd kernel_platform
         cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}.patch ./common/ || true
         mkdir -p ./common/fs ./common/include/linux ./common/lib ./common/crypto
         cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/ || true
         cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/ || true
         cp -r ../SukiSU_patch/other/lz4k/include/linux/* ./common/include/linux || true
         cp -r ../SukiSU_patch/other/lz4k/lib/* ./common/lib || true
         cp -r ../SukiSU_patch/other/lz4k/crypto/* ./common/crypto || true
         cd ./common
         PATCH_FILE=50_add_susfs_in_gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}.patch
         if [[ -f "$PATCH_FILE" ]]; then
         sed -i 's/-32,12 +32,38/-32,11 +32,37/g' "$PATCH_FILE"
         sed -i '/#include <trace\/hooks\/fs.h>/d' "$PATCH_FILE"
         patch -p1 < "$PATCH_FILE" || true
         fi
         cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
         patch -p1 -F 3 < syscall_hooks.patch || true
         echo "✅ SUSFS 和 syscall_hooks patch 应用完成"

      - name: Apply lz4kd Patches
        run: |
         set -e
         cd kernel_workspace/kernel_platform/common
         PATCH_FILE=../../SukiSU_patch/other/lz4k_patch/${{ inputs.KERNEL_VERSION }}/lz4kd.patch
         if [[ -f "$PATCH_FILE" ]]; then
         cp "$PATCH_FILE" ./lz4kd.patch
         patch -p1 -F 3 < lz4kd.patch || true
         else
         echo "❗ lz4kd patch not found for kernel version ${{ inputs.KERNEL_VERSION }}"
         fi

      - name: Add SUSFS Configuration Settings
        run: |
         set -e
         DEFCONFIG=kernel_workspace/kernel_platform/common/arch/arm64/configs/gki_defconfig.gki
         {
         echo "CONFIG_KSU=y"
         echo "CONFIG_KSU_SUSFS=y"
         echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y"
         echo "CONFIG_KSU_SUSFS_SUS_PATH=y"
         echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y"
         echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y"
         echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y"
         echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y"
         echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n"
         echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y"
         echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y"
         echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y"
         echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y"
         echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y"
         echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y"
         echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y"
         echo "CONFIG_CRYPTO_LZ4KD=y"
         } >> $DEFCONFIG
         
         if [[ "${{ inputs.kernelsu_variant }}" == "SukiSU-Ultra" ]]; then
         echo "CONFIG_KPM=y" >> $DEFCONFIG
         fi

         if [[ "${{ inputs.VFS_patch_ENABLED }}" == "enable" ]]; then
         echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> $DEFCONFIG
         echo "CONFIG_KSU_MANUAL_HOOK=y" >> $DEFCONFIG
         else
         echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> $DEFCONFIG
         fi
         sed -i 's/check_defconfig//' kernel_workspace/kernel_platform/common/build.config.gki
         echo "✅ SUSFS & defconfig 设置完成"

      - name: Add make name
        run: |
         cd kernel_workspace/kernel_platform
         KERNEL_NAME="${{ inputs.KERNEL_NAME }}"
         sed -i '$s|echo "\$res"|echo "$KERNEL_NAME"|' ./common/scripts/setlocalversion

      - name: Build kernel
        run: |
          cd kernel_workspace
          if [[ "${{ inputs.CPU }}" == "sm8650" || "${{ inputs.CPU }}" == "sm8750" ]]; then
            ./kernel_platform/build_with_bazel.py -t ${{ inputs.CPUD }} gki --action_env=KSU_VERSION
          else
            LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ inputs.CPUD }} gki
          fi

      - name: Make AnyKernel3
        run: |
         ls -l
         git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
         rm -rf ./AnyKernel3/.git
         cp kernel_workspace/out/dist/Image ./AnyKernel3/
         
         
      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
         name: AnyKernel3_sukisu_${{ env.KSUVER }}_ace2
         path: ./AnyKernel3/*
