name: Build All（支持每个分工作流自定义 KERNEL_NAME）

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: "默认内核版本名（可为空）"
        required: false
        default: ''

      ace2:
        description: "Build ace2"
        type: boolean
        default: false
      ace2_kernel:
        description: "ace2 内核版本名（可为空）"
        required: false
        default: ''

      ace2pro:
        description: "Build ace2pro"
        type: boolean
        default: false
      ace2pro_kernel:
        description: "ace2pro 内核版本名（可为空）"
        required: false
        default: ''

      acepro:
        description: "Build acepro"
        type: boolean
        default: false
      acepro_kernel:
        description: "acepro 内核版本名（可为空）"
        required: false
        default: ''

      ace3:
        description: "Build ace3"
        type: boolean
        default: false
      ace3_kernel:
        description: "ace3 内核版本名（可为空）"
        required: false
        default: ''

      ace3v:
        description: "Build ace3v"
        type: boolean
        default: false
      ace3v_kernel:
        description: "ace3v 内核版本名（可为空）"
        required: false
        default: ''

      ace5:
        description: "Build ace5"
        type: boolean
        default: false
      ace5_kernel:
        description: "ace5 内核版本名（可为空）"
        required: false
        default: ''

      oneplus12:
        description: "Build oneplus12"
        type: boolean
        default: false
      oneplus12_kernel:
        description: "oneplus12 内核版本名（可为空）"
        required: false
        default: ''

      oneplus12r:
        description: "Build oneplus12r"
        type: boolean
        default: false
      oneplus12r_kernel:
        description: "oneplus12r 内核版本名（可为空）"
        required: false
        default: ''

      padpro:
        description: "Build padpro"
        type: boolean
        default: false
      padpro_kernel:
        description: "padpro 内核版本名（可为空）"
        required: false
        default: ''

jobs:
  ace2:
    if: ${{ github.event.inputs.ace2 == 'true' }}
    uses: ./.github/workflows/ace2.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.ace2_kernel || github.event.inputs.kernel_name }}

  ace2pro:
    if: ${{ github.event.inputs.ace2pro == 'true' }}
    uses: ./.github/workflows/ace2pro.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.ace2pro_kernel || github.event.inputs.kernel_name }}

  acepro:
    if: ${{ github.event.inputs.acepro == 'true' }}
    uses: ./.github/workflows/acepro.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.acepro_kernel || github.event.inputs.kernel_name }}

  ace3:
    if: ${{ github.event.inputs.ace3 == 'true' }}
    uses: ./.github/workflows/ace3.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.ace3_kernel || github.event.inputs.kernel_name }}

  ace3v:
    if: ${{ github.event.inputs.ace3v == 'true' }}
    uses: ./.github/workflows/ace3v.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.ace3v_kernel || github.event.inputs.kernel_name }}

  ace5:
    if: ${{ github.event.inputs.ace5 == 'true' }}
    uses: ./.github/workflows/ace5.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.ace5_kernel || github.event.inputs.kernel_name }}

  oneplus12:
    if: ${{ github.event.inputs.oneplus12 == 'true' }}
    uses: ./.github/workflows/oneplus12.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.oneplus12_kernel || github.event.inputs.kernel_name }}

  oneplus12r:
    if: ${{ github.event.inputs.oneplus12r == 'true' }}
    uses: ./.github/workflows/oneplus12r.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.oneplus12r_kernel || github.event.inputs.kernel_name }}

  padpro:
    if: ${{ github.event.inputs.padpro == 'true' }}
    uses: ./.github/workflows/padpro.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.padpro_kernel || github.event.inputs.kernel_name }}
