name: Extra (oneplus13,11,13t,ace5,ace3pro)

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: "内核版本名 (不输入则默认)"
        required: false
        default: '-android15-8-g013ec21bba94-383916444'
      ace5pro:
        description: "Build ace5pro"
        type: boolean
        default: false
      oneplus13:
        description: "Build oneplus13"
        type: boolean
        default: false
      oneplus13t:
        description: "Build oneplus13t"
        type: boolean
        default: false
      ace3pro:
        description: "Build ace3pro"
        type: boolean
        default: false
      oneplus11:
        description: "Build oneplus11"
        type: boolean
        default: false

jobs:
  ace5pro:
    if: ${{ github.event.inputs.ace5pro == 'true' }}
    uses: ./.github/workflows/ace5pro.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.kernel_name }}

  oneplus13:
    if: ${{ github.event.inputs.oneplus13 == 'true' }}
    uses: ./.github/workflows/oneplus13.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.kernel_name }}

  oneplus13t:
    if: ${{ github.event.inputs.oneplus13t == 'true' }}
    uses: ./.github/workflows/oneplus13t.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.kernel_name }}

  ace3pro:
    if: ${{ github.event.inputs.ace3pro == 'true' }}
    uses: ./.github/workflows/ace3pro.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.kernel_name }}

  oneplus11:
    if: ${{ github.event.inputs.oneplus11 == 'true' }}
    uses: ./.github/workflows/oneplus11.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ github.event.inputs.kernel_name }}
