name: Build All

on:
  workflow_dispatch:

jobs:
  #ace2:
    #uses: ./.github/workflows/ace2.yml
    #secrets: inherit

  #ace2pro:
    #uses: ./.github/workflows/ace2pro.yml
    #secrets: inherit
    
  #acepro:
    #uses: ./.github/workflows/acepro.yml
    #secrets: inherit

  #ace3pro:
    #uses: ./.github/workflows/ace3pro.yml
    #secrets: inherit

  #ace3:
    #uses: ./.github/workflows/ace3.yml
    #secrets: inherit

  #ace3v:
    #uses: ./.github/workflows/ace3v.yml
    #secrets: inherit

  #ace5:
    #uses: ./.github/workflows/ace5.yml
    #secrets: inherit

  ace5pro:
    uses: ./.github/workflows/ace5pro.yml
    secrets: inherit

  oneplus13:
    uses: ./.github/workflows/oneplus13.yml
    secrets: inherit

  #oneplus12:
   #uses: ./.github/workflows/oneplus12.yml
   #secrets: inherit

  #oneplus11:
   #uses: ./.github/workflows/oneplus11.yml
   #secrets: inherit

  #oneplus12r:
   #uses: ./.github/workflows/oneplus12r.yml
   #secrets: inherit

  #padpro:
   #uses: ./.github/workflows/padpro.yml
   #secrets: inherit
